#!/usr/bin/env python3
"""Build immutable font assets for the GPU menu renderer.
Original font files and licenses live in hardware/fonts. BOOT uses only the
generated coverage assets; the phone runs no font rasterizer or interpreter.
"""
import argparse, base64, hashlib, json, struct, zlib
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
SIZES = (12, 14, 16, 18, 20, 24, 28, 32, 36, 40, 48, 56, 64)
CHARS = ''.join(chr(c) for c in range(32,127)) + '°×–—…←→↑↓'
def generate(font_path, output, digits_path=None):
    data = bytearray(); entries = []
    characters = CHARS + ''.join(chr(c) for c in range(0x410,0x450)) + '\u0401\u0451'
    for size in SIZES:
        f = ImageFont.truetype(str(font_path), size=size)
        try:
            axes = f.get_variation_axes()
            f.set_variation_by_axes([500 if a['name'] == b'Weight' else a['default'] for a in axes])
        except OSError:
            pass
        faces=[(f,characters,0)]
        if digits_path is not None and size>=32:
            faces.append((ImageFont.truetype(str(digits_path),size=size),'0123456789.-',0xf000))
        for face,chars,offset in faces:
            for char in chars:
                left, top, right, bottom = face.getbbox(char, anchor='ls')
                w, h = max(0,right-left), max(0,bottom-top)
                im = Image.new('L', (max(1,w), max(1,h)))
                ImageDraw.Draw(im).text((-left,-top), char, font=face, fill=255, anchor='ls')
                mask = im.tobytes() if w*h else b''
                entries.append((size,offset+ord(char),len(data),w,h,left,top,round(face.getlength(char)*64)))
                data.extend(mask)
    packed = base64.b64encode(zlib.compress(bytes(data),9)).decode()
    source_hash = hashlib.sha256(font_path.read_bytes()).hexdigest()
    text = '// Code generated by tools/build_ui_masks.py; DO NOT EDIT.\n'
    text += '// Immutable font coverage assets. Source SHA256: '+source_hash+'\npackage fb\n\n'
    text += 'const uiMaskRawBytes = '+str(len(data))+'\n'
    text += 'const uiMaskZlib = "'+packed+'"\n'
    text += 'var uiGlyphTable = [...]maskEntry{\n'
    for e in entries: text += '{'+','.join(map(str,e))+'},\n'
    text += '}\n'
    output.write_text(text)
    print(json.dumps({'font_input_sha256':source_hash,'font_file_shipped':False,'mask_bytes':len(data),'glyphs':len(entries),'output':str(output)},indent=2))
if __name__ == '__main__':
    p=argparse.ArgumentParser();p.add_argument('font',type=Path);p.add_argument('output',type=Path)
    p.add_argument('--digits',type=Path)
    a=p.parse_args();generate(a.font,a.output,a.digits)
